#!/bin/sh
#
# Categorisation happens here. Keep it clean.

# Pretty
source_if() {
  if [ -f $1 ]; then
    source $1
  fi
}

source_if ~/.dotfiles/files/bashrc._git     # Git related scripts
source_if ~/.dotfiles/files/bashrc.unix     # Unix tools
source_if ~/.dotfiles/files/bashrc.mac      # Stuff that works only on Macs
source_if ~/.dotfiles/files/bashrc.housing  # Housing
source_if ~/.dotfiles/files/bashrc.razorpay # Razorpay
source_if ~/.dotfiles/files/bashrc.apps     # Scripts that expect some stuff to be installed
source_if ~/.dotfiles/files/bashrc.path     # $PATH config
source_if ~/.dotfiles/files/bashrc.vars     # Env variables for various projects
source_if ~/.dotfiles/files/bashrc.vm       # VM things

dot() {
  sublime ~/.dotfiles
  cd ~/.dotfiles
}

# Tennis DB and AR mimic
tennis(){
    cd ~/workplace/tennis
    psql atpdatabase2017
}
